name: Tests

on: [push]

jobs:
  build-and-test:

    runs-on: windows-latest
    permissions:
      contents: read
      statuses: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Build
      run: dotnet build -c Release Simple.CommandsAndQueries\Simple.CommandsAndQueries.csproj

    - name: Test net6
      run: dotnet test Simple.CommandsAndQueries.Tests\Simple.CommandsAndQueries.Tests.csproj -c Release --framework net6.0 -l "console;verbosity=normal" -l "trx;logfilename=Net6TestResults.trx"

    - name: Test net7
      run: dotnet test Simple.CommandsAndQueries.Tests\Simple.CommandsAndQueries.Tests.csproj -c Release --framework net7.0 -l "console;verbosity=normal" -l "trx;logfilename=Net7TestResults.trx"
